### ISSUE TITLE
为啥不fork pacman

### ISSUE THREAD

**Issue by HADB** [coneycode/coney#10]
既然是基于pacman做的，为啥不fork它呢？那样岂不是可以更方便地将pacman中最新的改动merge进来？

**Comment by coneycode** [comment]
原因很多吧。。当时github用的还不熟。没想这么多，下了一堆主题试。然后用到这个了一顿改，改完了才放到github上的。其实他也是用的默认主题做出自己的样子，然后我用了他的ui，添加了自己的很多东西，我在所有介绍主题的地方都声明过用pacman的，还是很尊重作者的，这样。。

**Comment by HADB** [comment]
哦
