### ISSUE TITLE
关于评论的问题

### ISSUE THREAD

**Issue by lyjamare** [coneycode/coney#12]
我用了你的主题
使用后，评论栏，自动就有五个评论？
这个可以删除吗？

**Comment by coneycode** [comment]
给个地址？自动五个评论？

**Comment by lyjamare** [comment]
我的那个是搭在本地测试，还没有上线

**Comment by coneycode** [comment]
额，建议你看看多说。评论是多说提供的。另外。咱俩是同学啊。。哈哈，我是软院的耿彪
2015年3月27日 下午5:18于 "LeeYJ" <notifications@github.com>写道：

**Comment by lyjamare** [comment]
ok，收到，多谢学长了
