### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by wzshare** [coneycode/coney#13]
刚接触github，还不太会用，只好直接留言把我的想法说出来。今天用了你的主题，很不错。不过遇到了作者头像无法显示的问题。找来找去，貌似coney/source/css/_partial/aside.styl中的一处错误导致，在.author-logo中的background no-repeat url(root +author-img) left top这一句会产生路径的错误，导致作者的头像显示不出来，应该改为 root +"/"+author-img 。我对前端语言只知道个大概，所以不知道是不是这里导致的，不过修改后确实解决了问题。个人水平有限，请谨慎参考。谢谢。

**Comment by coneycode** [comment]
你用的是hexo3.0？

**Comment by wzshare** [comment]
是的，我应该直接下载的最新的

**Comment by coneycode** [comment]
那大概明白了。。对3.0的支持不太好。。-_-!

**Comment by yovenny** [comment]
hexo3.0果然适用，哈哈
