### ISSUE TITLE
修改_config.yml的主题颜色没变化

### ISSUE THREAD

**Issue by rico93** [coneycode/coney#6]
coney\source\css\_base\variable.styl 中看到17行 theme = convert(hexo-config("theme_color.theme"))和接下来的if 似乎无法把设置的颜色读入。尝试直接 color-theme = theme 直接报错说收到call ：convert("#颜色编码")，这个应该怎么修改。convert是在哪定义的函数呢

**Comment by coneycode** [comment]
http://gengbiao.me/hexo/coney主题的博客颜色更改/
更新stylus版本即可。hexo官方提供的版本略低，目前不支持颜色读取。
