### ISSUE TITLE
layout/_partial/head.ejs中前几行是不是有作者个人的网站信息？

### ISSUE THREAD

**Issue by tufu9441** [coneycode/coney#7]
就是360，百度和google的site-verification，这个是不是可以去掉？

**Comment by coneycode** [comment]
擦。。忘了。。是的，我去取消。。

**Comment by tufu9441** [comment]
@coneycode 另外，我在head.ejs中发现了好几行跟twitter有关的代码，添加meta name之类的，请问这些有什么用啊？

**Comment by coneycode** [comment]
-_-!么用。我当时自己调试的时候忘记删了。。最近太忙了，抱歉。才看到。
