### ISSUE TITLE
添加了一个返回顶部按钮，但还未完美

### ISSUE THREAD

**Issue by tufu9441** [coneycode/coney#9]
我在我自己Fork的Coney主题目录下添加了一个效果非常不错的返回顶部小火箭（具体在我[博客的首页](http://haomwei.com)就能看到），放在layout/_partial/totop.ejs里，但是目前我是把CSS直接写在这个文件里了，前后用style标签把它包起来，因为我尝试改写成stylus格式的放在css/_partial文件夹里没弄出来，应该还是语法没弄对吧。你若有空的话能不能麻烦把它整合成一个totop.styl以便于放在css里呢？多谢～

**Comment by coneycode** [comment]
好的。我明天晚上搞搞~
